# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'Photoshop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for Photoshop
  pod 'SnapKit', '~> 4.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ESPullToRefresh'
  pod 'KeychainAccess'
  pod 'CropViewController'
  pod 'HandyJSON'   #,' 4.1.1'
  pod 'Bugly'
  pod 'GPUImageBeautifyFilter'
  pod 'GPUImage', '~> 0.1.7'
  pod 'EFColorPicker', '1.1.0'
  pod 'Hero'
  pod 'CircleMenu', '3.1.0'

  #  pod 'Spring'
  #  pod 'RAMAnimatedTabBarController' , ' 3.5.0'
  #  pod 'RxSwift', '~> 4.0'
  #  pod 'RxCocoa', '~> 4.0'
  #  pod 'Kingfisher', '4.9.0'
  #  pod 'EVGPUImage2', '~> 0.2.0'
  #  pod 'YPImagePicker'
  #  pod 'XLActionController'  ,' 4.0.0'
  #  pod 'Moya', '~> 11.0'
end
